[build]
  base = "public"
  publish = "public"
  command = "npm run build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
[[[plugins]]]
  package = "@netlify/plugin-nextjs"